### ISSUE TITLE
Checklist for intersections release

### ISSUE THREAD

**Issue by AlexLoyko** [PeliasIntersections/api#1]
- [x]  Acceptance-tests https://github.com/pelias/acceptance-tests
- [x]  GSONIFY Street1 and Street2 helper/geojspnify_place_details
- [x]  Query(finilize the support for all the params)
- [x]  Parsing
